routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

# Tasks Routes
Route::resource('tasks', 'TasksController')->middleware('auth');
Route::get('tasks/changestatus/{id}/{sid}', 'TasksController@changeStatus')->name('tasks.changestatus')->middleware('auth');

Route::get('tasks/delete/{id}', 'TasksController@destroy')->name('tasks.delete')->middleware('auth');

Route::get('tasks/changeuser/{tid}/{uid?}', 'TasksController@changeUser')->name('task.changeuser')->middleware('auth');

Route::get('mytasks', 'TasksController@myTasks')->name('tasks.mytasks')->middleware('auth');

Route::get('completedtasks', 'TasksController@completedTasks')->name('tasks.completedtasks')->middleware('auth');

Route::delete('deleteall', 'TasksController@deleteAll')->name('tasks.deleteall')->middleware('auth');


# Tools Routes
Route::resource('tools', 'ToolsController')->middleware('auth');

Route::get('tools/changeuser/{tl_id}/{uid?}', 'ToolsController@changeUser')->name('tools.changeuser')->middleware('auth');

Route::get('tools/changestatus/{tl_id}/{sid?}', 'ToolsController@changeStatus')->name('tools.changestatus')->middleware('auth');

Route::get('mytools', 'ToolsController@myTools')->name('tools.mytools')->middleware('auth');

Route::get('availabletools', 'ToolsController@availableTools')->name('tools.availabletools')->middleware('auth');

Route::get('tools/delete/{id}', 'ToolsController@destroy')->name('tools.delete')->middleware('auth');




# Laravel Routes
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/Tool.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tool extends Model
{
    protected $fillable = [
        'name', 'notes','user_id','status_id'
    ];
    public function user(){
        return $this->belongsTo('App\User');
    }

    public function toolstatus(){
        return $this->belongsTo('App\Toolstatus','status_id');
    }
}

app/Http/Controllers/ToolsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tool;
use App\User;
use App\Toolstatus;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;

class ToolsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function availableTools()
    {        
        $tools=Tool::select('*')->where([['status_id',1],])->paginate('5');
        $tools->status_id = 1;
        $users = User::all();
        $statuses = Toolstatus::all();        
        return view('tools.index', compact('tools','users','statuses')); 
    }

    public function myTools()
    {        
        $tools = Tool::join('users','users.id','=','tools.user_id')->where([['user_id',Auth::id()],])->paginate('5');;
        $users = User::all();
        $statuses = Toolstatus::all();        
        return view('tools.index', compact('tools','users','statuses')); 
    }

    public function changeUser($tl_id, $uid = null){
        $tool = Tool::findOrFail($tl_id);
        $tool->user_id = $uid;
        $tool->status_id = 2;
        $tool->save(); 
        return back();

    }


    public function changeStatus($tl_id, $sid)
    {
        $tool = Tool::findOrFail($tl_id);    
        if($tool->status_id==$sid) return back();
        $tool->status_id = $sid;
        $tool->user_id = NULL;
        $tool->save();
        return back();
    } 


    public function index()
    {
        $tools=Tool::paginate(5);
        $users=User::all();
        $statuses=Toolstatus::all();
        return view('tools.index', compact('tools','users','statuses')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Gate::authorize('is-manager');
        return view('tools.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->name == NULL || $request->notes == NULL){
            Session::flash('NotFullForm', 'Please fill out the entire form, all fields are mandatory');
            return back();
        }
        $tool = new Tool();
        $tool=$tool->create($request->all());
        $tool->save();
        return redirect('tools');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Gate::authorize('is-manager');
        $tool = Tool::findOrFail($id);
        $statuses = Toolstatus::all();
        return view('tools.edit', compact('tool','statuses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request->name == NULL || $request->notes == NULL){
            Session::flash('NotFullForm', 'Please fill out the entire form, all fields are mandatory');
            return back();
        }
        $tool = Tool::findOrFail($id);
        $tool->update($request->all());     
        return redirect('tools');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Gate::authorize('is-manager');
        $tool = Tool::findOrFail($id);
        $tool->delete();
        return redirect('tools');
    }
}

resources/views/tools/create.blade.php
@extends('layouts.app')



@section('content')
@include('layouts.headers.list')
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">{{ __('Create Tool') }}</h3>
                        </div>
                    </div>
                </div>
@if(Session::has('NotFullForm'))
<div class = 'alert alert-danger'>
    {{Session::get('NotFullForm')}}
</div>
@endif

<div class="container"> 
    <div class="col"> 
        <form method = "post" action = "{{action('ToolsController@store')}}">
        @csrf 
        <div class="form-group">
            <label for = "name">Name</label>
            <input type = "text" class="form-control" name = "name">
        </div>     
        <div class="form-group">
            <label for = "tool_description">Notes</label>
            <input type = "text" class="form-control" name = "notes">
        </div>

        <div>
            <input type = "submit" name = "submit" class="btn btn-sm btn-default" value = "Add Tool">
        </div>                       
        </form> 
    </div>
</div> 
@endsection

resources/views/tools/edit.blade.php
@extends('layouts.app')


@section('content')
@include('layouts.headers.list')
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">{{ __('Edit Tool') }}</h3>
                        </div>
                    </div>
                </div>
@if(Session::has('NotFullForm'))
<div class = 'alert alert-danger'>
    {{Session::get('NotFullForm')}}
</div>
@endif
<div class="container"> 
    <div class="col"> 
        <form method = "post" action = "{{action('ToolsController@update', $tool->id)}}">
        @csrf
        @METHOD('PATCH')
             <div class="form-group">
            <label for = "name"><b>Name</b></label>
            <input type = "text" class="form-control" name = "name" value = {{$tool->name}}>
        </div>     
        <div class="form-group">
            <label for = "start_date"><b>Notes</b></label>
            <input type = "text" class="form-control" name = "notes" value = {{$tool->notes}}>
        </div>
        <div>
            <input type = "submit" name = "submit" class="btn btn-sm btn-default" value = "Update Tool">
        </div>

        </form> 
    </div>
</div> 
@endsection

resources/views/tools/index.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.headers.list')

    <div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0"><a href="{{ route('tools.index') }}" font-color:black>{{ __('Tools') }}</a></h3>
                        </div> 
                        <div class="col-4 text-right">
                        @if(Gate::allows('is-manager'))   
                            <a href="{{url('/tools/create')}}" class="btn btn-sm btn-primary">{{ __('Add New Tool') }}</a>
                        @endif  
                        </div>
                        
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">{{ __('Id') }}</th>
                                <th scope="col">{{ __('Name') }}</th>
                                <th scope="col">{{ __('Notes') }}</th>
                                <th scope="col">{{ __('Employees') }}</th>
                                <th scope="col">{{ __('Status') }}</th>
                                <th scope="col">{{ __('Created') }}</th>
                                <th scope="col">{{ __('Updated') }}</th>
                            </tr>
                        </thead>      

                        <tbody>
                        @foreach($tools as $tool)
                                <tr>
                                <td>{{$tool->id}}</td>
                                <td>{{$tool->name}}</td>
                                <td>{{$tool->notes}}</td>        
                                <td> 
                                @if($tool->status_id !=4) 
                                        
                                    @if(isset($tool->user_id))
                                      {{$tool->user->name}}  
                                    @else
                                    <div class="dropdown">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      Assign User
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    @foreach($users as $user)
                                    <a class="dropdown-item" href="{{route('tools.changeuser',[$tool->id,$user->id])}}">{{$user->name}}</a>
                                    @endforeach
                                    </div>
                                    </div>
                                    @endif 
                                @else
                                      Can't Assign Employee
                                @endif 
                                </td>
                                <td>          
                                <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @if(isset($tool->status_id))
                                      {{$tool->toolstatus->name}}  
                                    @endif
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                @foreach($statuses as $status)
                                    @if($status->id != $tool->status_id && $status->id != 2)
                                        <a class="dropdown-item" href="{{route('tools.changestatus',[$tool->id,$status->id])}}">{{$status->name}}</a>
                                    @endif
                                @endforeach
                                </div>
                              </div>  
                                </td>
                                <td>{{$tool->created_at}}</td>
                                <td>{{$tool->updated_at}}</td>

                                @if(Gate::allows('is-manager'))
                                <td class="text-right">
                                    <div class="dropdown">
                                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                                            <i class="fas fa-ellipsis-v"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                      
                                          <form action="{{ route('tools.destroy', $tool) }}" method="post">
                                              @csrf
                                              @method('delete')
                                             
                                              <a class="dropdown-item" href="{{route('tools.edit',$tool->id)}}">{{ __('Edit') }}</a>
                                             
                                              <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this tool?") }}') ? this.parentElement.submit() : ''">
                                                  {{ __('Delete') }}
                                              </button>
                                              @endif
                                          </form>    
                                            
                                                
                                        </div>
                                    </div>
                                </td>
                                    
                              </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $tools->links() }}
                </div>
                
            </div>
        </div>
    </div>
        
    @include('layouts.footers.auth')
  </div>
@endsection
 